### PR TITLE
Allow including offlined media in AAF

### PR DESCRIPTION
**Pull request by arvidfm**
This PR makes it possible to add offlined media to an AAF by supplying `offline=True` to `import_dnxhd_essence`, in which case the data won't be written to the essence. The offlined media can then be relinked using e.g. the tape name in Avid Media Composer, allowing you to create sequences that refer to essences that have already been sent to Media Composer previously.

The PR also includes some additional setters and getters for convenience, along with some aesthetic formatting changes.

### CODE REVIEW

**Comment by markreidvfx** [comment]
Thank you for the contribution! I just have 2 things.
 - Why do we need to add `__init__ `methods to all these other classes? They have nothing to initialize, is it stylistic thing?
 - Would it be possible to add a unit test at some point?

**Comment by markreidvfx** [comment]
yes can we remove the `__init__` methods, not a huge fan of code that does nothing and wastes cpu cycles :p

For the unit test, just something simple that calls the function and writes a file and verifies the mob is there and the length, etc is set correct value.

something like the current import tests
https://github.com/markreidvfx/pyaaf2/blob/master/tests/test_import.py#L55

**Comment by arvidfm** [comment]
Thank you for merging the PR! Just wondering, are there any plans to put out a new stable version of pyaaf2 that will include these changes any time in the near future?

**Comment by markreidvfx** [comment]
No problem, thanks for the PR!

Yes I was planning to do one this month, but just want to get the dev branch merged first

https://github.com/markreidvfx/pyaaf2/tree/dev

It has the updated data model from the latest AAFSDK and adds support for the AAFs from the latest MC.
Just been running it through some further testing before I merge it.  Check it out if you have the time :)

**Pull request merged**
